### PR TITLE
Some more changes to NP++ Syntax Highlighting

### PR DESCRIPTION
**Pull request by Psy-Virus**
Hey there,
still using your theme and have some more changes that you may like.

I hope I put everything into the right order. If not, feel free to change anything as you like.
I didn't see any side effects yet.

:-)

### CODE REVIEW

**Comment by Psy-Virus** [comment]
Before:
np sth-before
After:
np sth-after

**Comment by classikd** [comment]
Hello Psy-virus,
Yeah i like that good job ! You are always welcome :)
I'm surprised I didn't see this wrong color^^
I will include this correct in the 0.2.2 version as soon as i can.
Thanks for the help

**Comment by Psy-Virus** [comment]
Thanks and you're welcome^^

> I'm surprised I didn't see this wrong color^^

It's like these missing semicolons. You see them the whole time and know they're there until they magically vanish... :D

**Comment by classikd** [comment]
Haha exactly ^^' But don't remind me bad memories, now I mainly develop in javascript and these  semicolons are no longer part of my life

**Pull request merged**
